version: '3.7'
services:
  php-fpm:
    image: php:7.2-fpm-alpine3.8
    container_name: php-fpm
    restart: always
    networks:
        - austin-local-common
    volumes:
      - ./php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
      # - ./test-php-app:/var/www/html
      - ./kuxiaoju-server:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./php-user-define.ini:/usr/local/etc/php/conf.d/php-user-define.ini
  nginx:
    image: nginx:1.19.2-alpine
    container_name: nginx
    restart: always
    ports:
        - 8080:80
    networks:
      - austin-local-common
    sysctls:
      - net.core.somaxconn=4096
      - net.ipv4.tcp_syncookies=0
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./test-php-app:/var/www/html
      - ./kuxiaoju-server:/var/www/html

networks:
    austin-local-common:
        external: true